# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-31 19:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_harvest_day_app', '0002_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garden_name', models.CharField(max_length=45)),
                ('garden_address', models.CharField(max_length=45)),
                ('ward_num', models.IntegerField()),
                ('plant_date', models.DateTimeField()),
                ('plans', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('users', models.ManyToManyField(related_name='gardens', to='free_harvest_day_app.User')),
            ],
        ),
    ]
