# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-31 21:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('free_harvest_day_app', '0003_contact_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='profile_pic_url',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
