# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-10-31 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('free_harvest_day_app', '0003_garden'),
    ]

    operations = [
        migrations.RenameField(
            model_name='garden',
            old_name='garden_name',
            new_name='garden',
        ),
    ]
